### ISSUE TITLE
Certain Apps display a Glitched cover over the actual Window

### ISSUE THREAD

**Issue by LunatiK-ExpiX** [ImSwordQueen/Win10to7Issues#107] opened 2024-11-20 05:25 UTC
### Before reporting your issue

- [X] My version of Windows is up to date (Atleast up to April 2024 as per update warning)
- [X] I'm running the latest version or the one prior of the Windows 10to7 Transformation Pack (I checked the changelog on the downloads page before opening the issue).

### What version of Windows 10 are you using the transformation pack on?

Windows 10 Home 22H2 19045.5131

### What version of the Transformation Pack are you having issues with?

21H2to7 3.5.4

### Summarise the issue

Whenever I try to view certain applications, there is a cover that displays over it, always with the top bar being visible. The one shown is more severe, but often it will result in multiple lines covering the Window that is supposed to be displayed

### Screenshots

![image](https://github.com/user-attachments/assets/18cf8bed-78a9-4c76-ae20-4e4a2353d3a3)

### How do you reproduce the bug/inaccuracy?

Unknown. Can't confirm how it happens, might be related to having DwmBlurGlass installed before the pack was installed.

### Expected behaviour

To view the window normally
(What do you expect me to write here?)

### Additional Context

This seems to happen with app that start out fullscreen before changing.

**Comment by LunatiK-ExpiX** [comment] 2024-11-20 05:31
I found out a few requirements too:
Discord's Game overlay must be enabled

Maybe it relates to Vencord's option to enable Windows' native title bar

**Comment by ImSwordQueen** [comment] 2024-11-20 13:27
I think it is an issue with game overlay and vencord's windows native title bar. try disabling native titlebar and see if it still happens.

**Comment by ImSwordQueen** [comment] 2024-11-23 13:49
I will assume this issue was caused by vencord. Closing this.

**Closed by ImSwordQueen** 2024-11-23 13:49 UTC
Labels: bug
