### ISSUE TITLE
Crashes randomly when opening File Explorer/programs, causing Win7 title bar fix to not work

### ISSUE THREAD

**Issue by ghost** [ImSwordQueen/Win10to7Issues#11] opened 2024-06-13 17:34 UTC
**Describe the bug**
> A clear and concise description of what the bug is:

Consistently and randomly crashing whenever opening a program (any and all) and/or opening File Explorer window, causing the title bar to revert back to old default size.

**To Reproduce**
> Steps to reproduce the behavior:

Restarting PC; DWMBlurGlass will crash again after some minutes (opening File Explorer window or any program) and will keep happening randomly, regardless. Title bar is always broken when DWMGBlurGlass crashes.
After DWM crashes, I try to untick and re-tick Restore Win7 style title bar size and hit save and it does nothing; the title bar is still default fat-sized)

**Screenshots**
> If applicable, add screenshots to help explain your problem:

![untitled](https://github.com/ImSwordQueen/Win10to7Issues/assets/172628964/803f9879-2514-45fa-a5f0-e7a0511adde0)

**Additional information (please complete the following information):**
 > OS Version : [**Windows 10 22H2 Build 19045.4529**]
 > Transformation Pack Version : [**3.5.1**]

**Additional context**
Restarted PC again; Restore Win7 style title bar size is OK, but, DWMBlurGlass will inevitably crash again when opening any program after some minutes (~2-5 minutes after logon) and when it crashes it always reverts the title bar back to default (fat) size as shown in the screenshot attached.

**Comment by AdityaKKhullar** [comment] 2024-06-14 03:36
She already said that you need to use the no glow version, that fixes all the problems.

Uninstall the existing transformation, use disk cleanup, update your windows fully and then reinstall the no glow version of the transformation pack. Everything should be fixed.

**Comment by smashednormal9** [comment] 2024-06-14 03:53
> She already said that you need to use the no glow version, that fixes all the problems.
> 
> Uninstall the existing transformation, use disk cleanup, update your windows fully and then reinstall the no glow version of the transformation pack. Everything should be fixed.

Why is it include and present if its buggy and not working in the first place? And furthermore, not recommended to be used at all? Why is it included then? Where's the sense in that?

**Comment by AdityaKKhullar** [comment] 2024-06-14 04:00
This isn't her main job, atleast she fixed it in like 6 hours and updated it on the download page. Not my problem that you're a lazy dumb fuck and can't even spend 5 seconds going through the comments. Learnt to appreciate someone's hard work - otherwise go make a transformation yourself.
![image](https://github.com/ImSwordQueen/Win10to7Issues/assets/72785876/64afb4d3-5ae9-4c86-84ba-c903485b1744)

**Comment by ImSwordQueen** [comment] 2024-06-14 12:00
Duplicate of #5.

Due to how the windhawk mod doesn't rehook after explorer crashes you have to go in windhawk and disable and re-enable the windows 7 caption buttons mod. This will be fixed in a future release

**Closed by ImSwordQueen** 2024-06-14 12:00 UTC
Labels: question
